[package]
name = "zrc_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = { version = "0.20.2" }
logos = "0.14.0"
zrc_diagnostics = { version = "0.1.0", path = "../zrc_diagnostics" }
zrc_utils = { version = "0.1.0", path = "../zrc_utils" }

[build-dependencies]
lalrpop = "0.20.2"

[dev-dependencies]
indoc = "2.0.5"