[package]
name = "zrc_cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "zrc"
path = "src/main.rs"

[dependencies]
zrc = { path = "../zrc" }
clap = { version = "4.5.4", features = ["derive"] }
mimalloc = "0.1.48"
